export const mockDrinksOne = {
  drinks: [
    {
      strDrink: 'Mudslinger',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/hepk6h1504885554.jpg',
      idDrink: '16041'
    },
    {
      strDrink: 'Smut',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rx8k8e1504365812.jpg',
      idDrink: '17141'
    },
    {
      strDrink: 'Mudslinger',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/hepk6h1504885554.jpg',
      idDrink: '16041'
    },
    {
      strDrink: 'Smut',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rx8k8e1504365812.jpg',
      idDrink: '17141'
    },
    {
      strDrink: 'Mudslinger',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/hepk6h1504885554.jpg',
      idDrink: '16041'
    },
    {
      strDrink: 'Smut',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rx8k8e1504365812.jpg',
      idDrink: '17141'
    },
    {
      strDrink: 'Mudslinger',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/hepk6h1504885554.jpg',
      idDrink: '16041'
    },
    {
      strDrink: 'Smut',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rx8k8e1504365812.jpg',
      idDrink: '17141'
    },
    {
      strDrink: 'Mudslinger',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/hepk6h1504885554.jpg',
      idDrink: '16041'
    },
    {
      strDrink: 'Smut',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rx8k8e1504365812.jpg',
      idDrink: '17141'
    },
    {
      strDrink: 'Mudslinger',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/hepk6h1504885554.jpg',
      idDrink: '16041'
    },
    {
      strDrink: 'Smut',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rx8k8e1504365812.jpg',
      idDrink: '17141'
    },
    {
      strDrink: 'Mudslinger',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/hepk6h1504885554.jpg',
      idDrink: '16041'
    },
    {
      strDrink: 'Smut',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rx8k8e1504365812.jpg',
      idDrink: '17141'
    },
    {
      strDrink: 'Mudslinger',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/hepk6h1504885554.jpg',
      idDrink: '16041'
    },
    {
      strDrink: 'Smut',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rx8k8e1504365812.jpg',
      idDrink: '17141'
    },
  ]
}

export const mockDrinksTwo = {
  drinks: [
    {
      idDrink: '12518',
      strDrink: 'Whisky Mac',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Ordinary Drink',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Collins Glass',
      strInstructions: 'Pour both of the ingredients into a wine goblet with no ice.',
      strInstructionsES: null,
      strInstructionsDE: 'Beide Zutaten in einen Weinkelch geben, ohne Eis.',
      strInstructionsFR: null,
      strInstructionsIT: 'Versare entrambi gli ingredienti in un calice da vino senza ghiaccio.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/yvvwys1461867858.jpg',
      strIngredient1: 'Scotch',
      strIngredient2: 'Wine',
      strIngredient3: null,
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 1/2 oz ',
      strMeasure2: '1 oz Green Ginger ',
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-04-28 19:24:18'
    }
  ]
}

export const mockDrinksThree = {
  drinks: [
    {
      idDrink: '11993',
      strDrink: 'Quentin',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Ordinary Drink',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Cocktail glass',
      strInstructions: 'In a shaker half-filled with ice cubes, combine the rum, Kahlua, and cream. Shake well. Strain into a cocktail glass and garnish with the nutmeg.',
      strInstructionsES: null,
      strInstructionsDE: 'In einem Shaker, der halb mit Eiswürfeln gefüllt ist, Rum, Kahlua und Sahne mischen. Gut schütteln. In ein Cocktailglas abseihen und mit der Muskatnuss garnieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'In uno shaker riempito a metà con cubetti di ghiaccio, unire il rum, il Kahlua e la panna. Filtrare in una coppetta da cocktail e guarnire con la noce moscata. Agitare bene.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/spxtqp1478963398.jpg',
      strIngredient1: 'Dark rum',
      strIngredient2: 'Kahlua',
      strIngredient3: 'Light cream',
      strIngredient4: 'Nutmeg',
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 1/2 oz ',
      strMeasure2: '1/2 oz ',
      strMeasure3: '1 oz ',
      strMeasure4: '1/8 tsp grated ',
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-11-12 15:09:58'
    },
    {
      idDrink: '11987',
      strDrink: 'Queen Bee',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Ordinary Drink',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Cocktail glass',
      strInstructions: 'Shake all ingredients with ice, strain into a cocktail glass, and serve.',
      strInstructionsES: null,
      strInstructionsDE: 'Alle Zutaten mit Eis schütteln, in ein Cocktailglas abseihen und servieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Shakerare tutti gli ingredienti con ghiaccio, filtrare in una coppetta da cocktail e servire.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rvvpxu1478963194.jpg',
      strIngredient1: 'Coffee brandy',
      strIngredient2: 'Lime vodka',
      strIngredient3: 'Sherry',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 oz ',
      strMeasure2: '1 1/2 oz ',
      strMeasure3: '1/2 oz cream ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-11-12 15:06:34'
    },
  ]
}

export const mockMealsOne = {
  meals: [
    {
      idMeal: '52965',
      strMeal: 'Breakfast Potatoes',
      strDrinkAlternate: null,
      strCategory: 'Breakfast',
      strArea: 'Canadian',
      strInstructions: "Before you do anything, freeze your bacon slices that way when you're ready to prep, it'll be so much easier to chop!\r\n" +
        'Wash the potatoes and cut medium dice into square pieces. To prevent any browning, place the already cut potatoes in a bowl filled with water.\r\n' +
        'In the meantime, heat 1-2 tablespoons of oil in a large skillet over medium-high heat. Tilt the skillet so the oil spreads evenly.\r\n' +
        'Once the oil is hot, drain the potatoes and add to the skillet. Season with salt, pepper, and Old Bay as needed.\r\n' +
        'Cook for 10 minutes, stirring the potatoes often, until brown. If needed, add a tablespoon more of oil.\r\n' +
        'Chop up the bacon and add to the potatoes. The bacon will start to render and the fat will begin to further cook the potatoes. Toss it up a bit! The bacon will take 5-6 minutes to crisp.\r\n' +
        'Once the bacon is cooked, reduce the heat to medium-low, add the minced garlic and toss. Season once more. Add dried or fresh parsley. Control heat as needed.\r\n' +
        'Let the garlic cook until fragrant, about one minute.\r\n' +
        'Just before serving, drizzle over the maple syrup and toss. Let that cook another minute, giving the potatoes a caramelized effect.\r\n' +
        'Serve in a warm bowl with a sunny side up egg!',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1550441882.jpg',
      strTags: 'Breakfast,Brunch,',
      strYoutube: 'https://www.youtube.com/watch?v=BoD0TIO9nE4',
      strIngredient1: 'Potatoes',
      strIngredient2: 'Olive Oil',
      strIngredient3: 'Bacon',
      strIngredient4: 'Garlic Clove',
      strIngredient5: 'Maple Syrup',
      strIngredient6: 'Parsley',
      strIngredient7: 'Salt',
      strIngredient8: 'Pepper',
      strIngredient9: 'Allspice',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '3 Medium',
      strMeasure2: '1 tbs',
      strMeasure3: '2 strips',
      strMeasure4: 'Minced',
      strMeasure5: '1 tbs',
      strMeasure6: 'Garnish',
      strMeasure7: 'Pinch',
      strMeasure8: 'Pinch',
      strMeasure9: 'To taste',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'http://www.vodkaandbiscuits.com/2014/03/06/bangin-breakfast-potatoes/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null
    }
  ]
} 

export const mockMealsTwo = {
  meals: [
    {
      idMeal: '52774',
      strMeal: 'Pad See Ew',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'Thai',
      strInstructions: 'Mix Sauce in small bowl.\r\n' +
        'Mince garlic into wok with oil. Place over high heat, when hot, add chicken and Chinese broccoli stems, cook until chicken is light golden.\r\n' +
        "Push to the side of the wok, crack egg in and scramble. Don't worry if it sticks to the bottom of the wok - it will char and which adds authentic flavour.\r\n" +
        'Add noodles, Chinese broccoli leaves and sauce. Gently mix together until the noodles are stained dark and leaves are wilted. Serve immediately!',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uuuspp1468263334.jpg',
      strTags: 'Pasta',
      strYoutube: 'https://www.youtube.com/watch?v=Ohy1DELF4is',
      strIngredient1: 'rice stick noodles',
      strIngredient2: 'dark soy sauce',
      strIngredient3: 'oyster sauce',
      strIngredient4: 'soy sauce',
      strIngredient5: 'white vinegar',
      strIngredient6: 'sugar',
      strIngredient7: 'water',
      strIngredient8: 'peanut oil',
      strIngredient9: 'garlic',
      strIngredient10: 'Chicken',
      strIngredient11: 'Egg',
      strIngredient12: 'Chinese broccoli',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '6oz/180g',
      strMeasure2: '2 tbsp',
      strMeasure3: '2 tbsp',
      strMeasure4: '2 tsp',
      strMeasure5: '2 tsp',
      strMeasure6: '2 tsp',
      strMeasure7: '2 tbsp',
      strMeasure8: '2 tbsp',
      strMeasure9: '2 cloves',
      strMeasure10: '1 cup',
      strMeasure11: '1',
      strMeasure12: '4 cups',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: null,
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null
    },
    {
      idMeal: '52780',
      strMeal: 'Potato Gratin with Chicken',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'Unknown',
      strInstructions: "15 minute potato gratin with chicken and bacon greens: a gratin always seems more effort and more indulgent than ordinary boiled or roasts, but it doesn't have to take 45mins, it's nice for a change and you can control the calorie content by going with full fat to low fat creme fraiche. (It's always tastes better full fat though obviously!) to serve 4: use 800g of potatoes, finely slice and boil in a pan for about 5-8 mins till firmish, not soft. Finely slice 3 onions and place in an oven dish with 2 tblsp of olive oil and 100ml of chicken stock. Cook till the onions are soft then drain the potatoes and pour onto the onions. Season and spoon over cream or creme fraiche till all is covered but not swimming. Grate Parmesan over the top then finish under the grill till nicely golden. serve with chicken and bacon, peas and spinach.",
      strMealThumb: 'https://www.themealdb.com/images/media/meals/qwrtut1468418027.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=p3u8eiy3yHI',
      strIngredient1: 'Potatoes',
      strIngredient2: 'Onions',
      strIngredient3: 'Olive Oil',
      strIngredient4: 'Chicken Stock',
      strIngredient5: 'Creme Fraiche',
      strIngredient6: 'Parmesan',
      strIngredient7: 'Chicken Breasts',
      strIngredient8: 'Bacon',
      strIngredient9: 'Spinach',
      strIngredient10: 'Peas',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '800g',
      strMeasure2: '3',
      strMeasure3: '2 tblsp',
      strMeasure4: '100ml',
      strMeasure5: '1 pot',
      strMeasure6: 'Topping',
      strMeasure7: '4',
      strMeasure8: '4',
      strMeasure9: 'Topping',
      strMeasure10: 'Topping',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: 'https://www.instagram.com/p/BHxR7hYBJ6P',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null
    },
    {
      idMeal: '52804',
      strMeal: 'Poutine',
      strDrinkAlternate: null,
      strCategory: 'Miscellaneous',
      strArea: 'Canadian',
      strInstructions: 'Heat oil in a deep fryer or deep heavy skillet to 365°F (185°C).\r\n' +
        'Warm gravy in saucepan or microwave.\r\n' +
        'Place the fries into the hot oil, and cook until light brown, about 5 minutes.\r\n' +
        'Remove to a paper towel lined plate to drain.\r\n' +
        'Place the fries on a serving platter, and sprinkle the cheese over them.\r\n' +
        'Ladle gravy over the fries and cheese, and serve immediately.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uuyrrx1487327597.jpg',
      strTags: 'UnHealthy,Speciality,HangoverFood',
      strYoutube: 'https://www.youtube.com/watch?v=UVAMAoA2_WU',
      strIngredient1: 'Vegetable Oil',
      strIngredient2: 'Beef Gravy',
      strIngredient3: 'Potatoes',
      strIngredient4: 'Cheese Curds',
      strIngredient5: '',
      strIngredient6: '',
      strIngredient7: '',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: 'Dash',
      strMeasure2: '1 Can',
      strMeasure3: '5 thin cut',
      strMeasure4: '2 cups',
      strMeasure5: '',
      strMeasure6: '',
      strMeasure7: '',
      strMeasure8: '',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'http://www.food.com/recipe/real-canadian-poutine-113388',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null
    },
    {
      idMeal: '52774',
      strMeal: 'Pad See Ew',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'Thai',
      strInstructions: 'Mix Sauce in small bowl.\r\n' +
        'Mince garlic into wok with oil. Place over high heat, when hot, add chicken and Chinese broccoli stems, cook until chicken is light golden.\r\n' +
        "Push to the side of the wok, crack egg in and scramble. Don't worry if it sticks to the bottom of the wok - it will char and which adds authentic flavour.\r\n" +
        'Add noodles, Chinese broccoli leaves and sauce. Gently mix together until the noodles are stained dark and leaves are wilted. Serve immediately!',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uuuspp1468263334.jpg',
      strTags: 'Pasta',
      strYoutube: 'https://www.youtube.com/watch?v=Ohy1DELF4is',
      strIngredient1: 'rice stick noodles',
      strIngredient2: 'dark soy sauce',
      strIngredient3: 'oyster sauce',
      strIngredient4: 'soy sauce',
      strIngredient5: 'white vinegar',
      strIngredient6: 'sugar',
      strIngredient7: 'water',
      strIngredient8: 'peanut oil',
      strIngredient9: 'garlic',
      strIngredient10: 'Chicken',
      strIngredient11: 'Egg',
      strIngredient12: 'Chinese broccoli',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '6oz/180g',
      strMeasure2: '2 tbsp',
      strMeasure3: '2 tbsp',
      strMeasure4: '2 tsp',
      strMeasure5: '2 tsp',
      strMeasure6: '2 tsp',
      strMeasure7: '2 tbsp',
      strMeasure8: '2 tbsp',
      strMeasure9: '2 cloves',
      strMeasure10: '1 cup',
      strMeasure11: '1',
      strMeasure12: '4 cups',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: null,
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null
    },
    {
      idMeal: '52780',
      strMeal: 'Potato Gratin with Chicken',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'Unknown',
      strInstructions: "15 minute potato gratin with chicken and bacon greens: a gratin always seems more effort and more indulgent than ordinary boiled or roasts, but it doesn't have to take 45mins, it's nice for a change and you can control the calorie content by going with full fat to low fat creme fraiche. (It's always tastes better full fat though obviously!) to serve 4: use 800g of potatoes, finely slice and boil in a pan for about 5-8 mins till firmish, not soft. Finely slice 3 onions and place in an oven dish with 2 tblsp of olive oil and 100ml of chicken stock. Cook till the onions are soft then drain the potatoes and pour onto the onions. Season and spoon over cream or creme fraiche till all is covered but not swimming. Grate Parmesan over the top then finish under the grill till nicely golden. serve with chicken and bacon, peas and spinach.",
      strMealThumb: 'https://www.themealdb.com/images/media/meals/qwrtut1468418027.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=p3u8eiy3yHI',
      strIngredient1: 'Potatoes',
      strIngredient2: 'Onions',
      strIngredient3: 'Olive Oil',
      strIngredient4: 'Chicken Stock',
      strIngredient5: 'Creme Fraiche',
      strIngredient6: 'Parmesan',
      strIngredient7: 'Chicken Breasts',
      strIngredient8: 'Bacon',
      strIngredient9: 'Spinach',
      strIngredient10: 'Peas',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '800g',
      strMeasure2: '3',
      strMeasure3: '2 tblsp',
      strMeasure4: '100ml',
      strMeasure5: '1 pot',
      strMeasure6: 'Topping',
      strMeasure7: '4',
      strMeasure8: '4',
      strMeasure9: 'Topping',
      strMeasure10: 'Topping',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: 'https://www.instagram.com/p/BHxR7hYBJ6P',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null
    },
    {
      idMeal: '52804',
      strMeal: 'Poutine',
      strDrinkAlternate: null,
      strCategory: 'Miscellaneous',
      strArea: 'Canadian',
      strInstructions: 'Heat oil in a deep fryer or deep heavy skillet to 365°F (185°C).\r\n' +
        'Warm gravy in saucepan or microwave.\r\n' +
        'Place the fries into the hot oil, and cook until light brown, about 5 minutes.\r\n' +
        'Remove to a paper towel lined plate to drain.\r\n' +
        'Place the fries on a serving platter, and sprinkle the cheese over them.\r\n' +
        'Ladle gravy over the fries and cheese, and serve immediately.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uuyrrx1487327597.jpg',
      strTags: 'UnHealthy,Speciality,HangoverFood',
      strYoutube: 'https://www.youtube.com/watch?v=UVAMAoA2_WU',
      strIngredient1: 'Vegetable Oil',
      strIngredient2: 'Beef Gravy',
      strIngredient3: 'Potatoes',
      strIngredient4: 'Cheese Curds',
      strIngredient5: '',
      strIngredient6: '',
      strIngredient7: '',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: 'Dash',
      strMeasure2: '1 Can',
      strMeasure3: '5 thin cut',
      strMeasure4: '2 cups',
      strMeasure5: '',
      strMeasure6: '',
      strMeasure7: '',
      strMeasure8: '',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'http://www.food.com/recipe/real-canadian-poutine-113388',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null
    },
    {
      idMeal: '52774',
      strMeal: 'Pad See Ew',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'Thai',
      strInstructions: 'Mix Sauce in small bowl.\r\n' +
        'Mince garlic into wok with oil. Place over high heat, when hot, add chicken and Chinese broccoli stems, cook until chicken is light golden.\r\n' +
        "Push to the side of the wok, crack egg in and scramble. Don't worry if it sticks to the bottom of the wok - it will char and which adds authentic flavour.\r\n" +
        'Add noodles, Chinese broccoli leaves and sauce. Gently mix together until the noodles are stained dark and leaves are wilted. Serve immediately!',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uuuspp1468263334.jpg',
      strTags: 'Pasta',
      strYoutube: 'https://www.youtube.com/watch?v=Ohy1DELF4is',
      strIngredient1: 'rice stick noodles',
      strIngredient2: 'dark soy sauce',
      strIngredient3: 'oyster sauce',
      strIngredient4: 'soy sauce',
      strIngredient5: 'white vinegar',
      strIngredient6: 'sugar',
      strIngredient7: 'water',
      strIngredient8: 'peanut oil',
      strIngredient9: 'garlic',
      strIngredient10: 'Chicken',
      strIngredient11: 'Egg',
      strIngredient12: 'Chinese broccoli',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '6oz/180g',
      strMeasure2: '2 tbsp',
      strMeasure3: '2 tbsp',
      strMeasure4: '2 tsp',
      strMeasure5: '2 tsp',
      strMeasure6: '2 tsp',
      strMeasure7: '2 tbsp',
      strMeasure8: '2 tbsp',
      strMeasure9: '2 cloves',
      strMeasure10: '1 cup',
      strMeasure11: '1',
      strMeasure12: '4 cups',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: null,
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null
    },
    {
      idMeal: '52780',
      strMeal: 'Potato Gratin with Chicken',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'Unknown',
      strInstructions: "15 minute potato gratin with chicken and bacon greens: a gratin always seems more effort and more indulgent than ordinary boiled or roasts, but it doesn't have to take 45mins, it's nice for a change and you can control the calorie content by going with full fat to low fat creme fraiche. (It's always tastes better full fat though obviously!) to serve 4: use 800g of potatoes, finely slice and boil in a pan for about 5-8 mins till firmish, not soft. Finely slice 3 onions and place in an oven dish with 2 tblsp of olive oil and 100ml of chicken stock. Cook till the onions are soft then drain the potatoes and pour onto the onions. Season and spoon over cream or creme fraiche till all is covered but not swimming. Grate Parmesan over the top then finish under the grill till nicely golden. serve with chicken and bacon, peas and spinach.",
      strMealThumb: 'https://www.themealdb.com/images/media/meals/qwrtut1468418027.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=p3u8eiy3yHI',
      strIngredient1: 'Potatoes',
      strIngredient2: 'Onions',
      strIngredient3: 'Olive Oil',
      strIngredient4: 'Chicken Stock',
      strIngredient5: 'Creme Fraiche',
      strIngredient6: 'Parmesan',
      strIngredient7: 'Chicken Breasts',
      strIngredient8: 'Bacon',
      strIngredient9: 'Spinach',
      strIngredient10: 'Peas',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '800g',
      strMeasure2: '3',
      strMeasure3: '2 tblsp',
      strMeasure4: '100ml',
      strMeasure5: '1 pot',
      strMeasure6: 'Topping',
      strMeasure7: '4',
      strMeasure8: '4',
      strMeasure9: 'Topping',
      strMeasure10: 'Topping',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: 'https://www.instagram.com/p/BHxR7hYBJ6P',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null
    },
    {
      idMeal: '52804',
      strMeal: 'Poutine',
      strDrinkAlternate: null,
      strCategory: 'Miscellaneous',
      strArea: 'Canadian',
      strInstructions: 'Heat oil in a deep fryer or deep heavy skillet to 365°F (185°C).\r\n' +
        'Warm gravy in saucepan or microwave.\r\n' +
        'Place the fries into the hot oil, and cook until light brown, about 5 minutes.\r\n' +
        'Remove to a paper towel lined plate to drain.\r\n' +
        'Place the fries on a serving platter, and sprinkle the cheese over them.\r\n' +
        'Ladle gravy over the fries and cheese, and serve immediately.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uuyrrx1487327597.jpg',
      strTags: 'UnHealthy,Speciality,HangoverFood',
      strYoutube: 'https://www.youtube.com/watch?v=UVAMAoA2_WU',
      strIngredient1: 'Vegetable Oil',
      strIngredient2: 'Beef Gravy',
      strIngredient3: 'Potatoes',
      strIngredient4: 'Cheese Curds',
      strIngredient5: '',
      strIngredient6: '',
      strIngredient7: '',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: 'Dash',
      strMeasure2: '1 Can',
      strMeasure3: '5 thin cut',
      strMeasure4: '2 cups',
      strMeasure5: '',
      strMeasure6: '',
      strMeasure7: '',
      strMeasure8: '',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'http://www.food.com/recipe/real-canadian-poutine-113388',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null
    },
    {
      idMeal: '52774',
      strMeal: 'Pad See Ew',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'Thai',
      strInstructions: 'Mix Sauce in small bowl.\r\n' +
        'Mince garlic into wok with oil. Place over high heat, when hot, add chicken and Chinese broccoli stems, cook until chicken is light golden.\r\n' +
        "Push to the side of the wok, crack egg in and scramble. Don't worry if it sticks to the bottom of the wok - it will char and which adds authentic flavour.\r\n" +
        'Add noodles, Chinese broccoli leaves and sauce. Gently mix together until the noodles are stained dark and leaves are wilted. Serve immediately!',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uuuspp1468263334.jpg',
      strTags: 'Pasta',
      strYoutube: 'https://www.youtube.com/watch?v=Ohy1DELF4is',
      strIngredient1: 'rice stick noodles',
      strIngredient2: 'dark soy sauce',
      strIngredient3: 'oyster sauce',
      strIngredient4: 'soy sauce',
      strIngredient5: 'white vinegar',
      strIngredient6: 'sugar',
      strIngredient7: 'water',
      strIngredient8: 'peanut oil',
      strIngredient9: 'garlic',
      strIngredient10: 'Chicken',
      strIngredient11: 'Egg',
      strIngredient12: 'Chinese broccoli',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '6oz/180g',
      strMeasure2: '2 tbsp',
      strMeasure3: '2 tbsp',
      strMeasure4: '2 tsp',
      strMeasure5: '2 tsp',
      strMeasure6: '2 tsp',
      strMeasure7: '2 tbsp',
      strMeasure8: '2 tbsp',
      strMeasure9: '2 cloves',
      strMeasure10: '1 cup',
      strMeasure11: '1',
      strMeasure12: '4 cups',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: null,
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null
    },
    {
      idMeal: '52780',
      strMeal: 'Potato Gratin with Chicken',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'Unknown',
      strInstructions: "15 minute potato gratin with chicken and bacon greens: a gratin always seems more effort and more indulgent than ordinary boiled or roasts, but it doesn't have to take 45mins, it's nice for a change and you can control the calorie content by going with full fat to low fat creme fraiche. (It's always tastes better full fat though obviously!) to serve 4: use 800g of potatoes, finely slice and boil in a pan for about 5-8 mins till firmish, not soft. Finely slice 3 onions and place in an oven dish with 2 tblsp of olive oil and 100ml of chicken stock. Cook till the onions are soft then drain the potatoes and pour onto the onions. Season and spoon over cream or creme fraiche till all is covered but not swimming. Grate Parmesan over the top then finish under the grill till nicely golden. serve with chicken and bacon, peas and spinach.",
      strMealThumb: 'https://www.themealdb.com/images/media/meals/qwrtut1468418027.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=p3u8eiy3yHI',
      strIngredient1: 'Potatoes',
      strIngredient2: 'Onions',
      strIngredient3: 'Olive Oil',
      strIngredient4: 'Chicken Stock',
      strIngredient5: 'Creme Fraiche',
      strIngredient6: 'Parmesan',
      strIngredient7: 'Chicken Breasts',
      strIngredient8: 'Bacon',
      strIngredient9: 'Spinach',
      strIngredient10: 'Peas',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '800g',
      strMeasure2: '3',
      strMeasure3: '2 tblsp',
      strMeasure4: '100ml',
      strMeasure5: '1 pot',
      strMeasure6: 'Topping',
      strMeasure7: '4',
      strMeasure8: '4',
      strMeasure9: 'Topping',
      strMeasure10: 'Topping',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: 'https://www.instagram.com/p/BHxR7hYBJ6P',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null
    },
    {
      idMeal: '52804',
      strMeal: 'Poutine',
      strDrinkAlternate: null,
      strCategory: 'Miscellaneous',
      strArea: 'Canadian',
      strInstructions: 'Heat oil in a deep fryer or deep heavy skillet to 365°F (185°C).\r\n' +
        'Warm gravy in saucepan or microwave.\r\n' +
        'Place the fries into the hot oil, and cook until light brown, about 5 minutes.\r\n' +
        'Remove to a paper towel lined plate to drain.\r\n' +
        'Place the fries on a serving platter, and sprinkle the cheese over them.\r\n' +
        'Ladle gravy over the fries and cheese, and serve immediately.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uuyrrx1487327597.jpg',
      strTags: 'UnHealthy,Speciality,HangoverFood',
      strYoutube: 'https://www.youtube.com/watch?v=UVAMAoA2_WU',
      strIngredient1: 'Vegetable Oil',
      strIngredient2: 'Beef Gravy',
      strIngredient3: 'Potatoes',
      strIngredient4: 'Cheese Curds',
      strIngredient5: '',
      strIngredient6: '',
      strIngredient7: '',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: 'Dash',
      strMeasure2: '1 Can',
      strMeasure3: '5 thin cut',
      strMeasure4: '2 cups',
      strMeasure5: '',
      strMeasure6: '',
      strMeasure7: '',
      strMeasure8: '',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'http://www.food.com/recipe/real-canadian-poutine-113388',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null
    },
    {
      idMeal: '52774',
      strMeal: 'Pad See Ew',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'Thai',
      strInstructions: 'Mix Sauce in small bowl.\r\n' +
        'Mince garlic into wok with oil. Place over high heat, when hot, add chicken and Chinese broccoli stems, cook until chicken is light golden.\r\n' +
        "Push to the side of the wok, crack egg in and scramble. Don't worry if it sticks to the bottom of the wok - it will char and which adds authentic flavour.\r\n" +
        'Add noodles, Chinese broccoli leaves and sauce. Gently mix together until the noodles are stained dark and leaves are wilted. Serve immediately!',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uuuspp1468263334.jpg',
      strTags: 'Pasta',
      strYoutube: 'https://www.youtube.com/watch?v=Ohy1DELF4is',
      strIngredient1: 'rice stick noodles',
      strIngredient2: 'dark soy sauce',
      strIngredient3: 'oyster sauce',
      strIngredient4: 'soy sauce',
      strIngredient5: 'white vinegar',
      strIngredient6: 'sugar',
      strIngredient7: 'water',
      strIngredient8: 'peanut oil',
      strIngredient9: 'garlic',
      strIngredient10: 'Chicken',
      strIngredient11: 'Egg',
      strIngredient12: 'Chinese broccoli',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '6oz/180g',
      strMeasure2: '2 tbsp',
      strMeasure3: '2 tbsp',
      strMeasure4: '2 tsp',
      strMeasure5: '2 tsp',
      strMeasure6: '2 tsp',
      strMeasure7: '2 tbsp',
      strMeasure8: '2 tbsp',
      strMeasure9: '2 cloves',
      strMeasure10: '1 cup',
      strMeasure11: '1',
      strMeasure12: '4 cups',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: null,
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null
    },
    {
      idMeal: '52780',
      strMeal: 'Potato Gratin with Chicken',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'Unknown',
      strInstructions: "15 minute potato gratin with chicken and bacon greens: a gratin always seems more effort and more indulgent than ordinary boiled or roasts, but it doesn't have to take 45mins, it's nice for a change and you can control the calorie content by going with full fat to low fat creme fraiche. (It's always tastes better full fat though obviously!) to serve 4: use 800g of potatoes, finely slice and boil in a pan for about 5-8 mins till firmish, not soft. Finely slice 3 onions and place in an oven dish with 2 tblsp of olive oil and 100ml of chicken stock. Cook till the onions are soft then drain the potatoes and pour onto the onions. Season and spoon over cream or creme fraiche till all is covered but not swimming. Grate Parmesan over the top then finish under the grill till nicely golden. serve with chicken and bacon, peas and spinach.",
      strMealThumb: 'https://www.themealdb.com/images/media/meals/qwrtut1468418027.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=p3u8eiy3yHI',
      strIngredient1: 'Potatoes',
      strIngredient2: 'Onions',
      strIngredient3: 'Olive Oil',
      strIngredient4: 'Chicken Stock',
      strIngredient5: 'Creme Fraiche',
      strIngredient6: 'Parmesan',
      strIngredient7: 'Chicken Breasts',
      strIngredient8: 'Bacon',
      strIngredient9: 'Spinach',
      strIngredient10: 'Peas',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '800g',
      strMeasure2: '3',
      strMeasure3: '2 tblsp',
      strMeasure4: '100ml',
      strMeasure5: '1 pot',
      strMeasure6: 'Topping',
      strMeasure7: '4',
      strMeasure8: '4',
      strMeasure9: 'Topping',
      strMeasure10: 'Topping',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: 'https://www.instagram.com/p/BHxR7hYBJ6P',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null
    },
    {
      idMeal: '52804',
      strMeal: 'Poutine',
      strDrinkAlternate: null,
      strCategory: 'Miscellaneous',
      strArea: 'Canadian',
      strInstructions: 'Heat oil in a deep fryer or deep heavy skillet to 365°F (185°C).\r\n' +
        'Warm gravy in saucepan or microwave.\r\n' +
        'Place the fries into the hot oil, and cook until light brown, about 5 minutes.\r\n' +
        'Remove to a paper towel lined plate to drain.\r\n' +
        'Place the fries on a serving platter, and sprinkle the cheese over them.\r\n' +
        'Ladle gravy over the fries and cheese, and serve immediately.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uuyrrx1487327597.jpg',
      strTags: 'UnHealthy,Speciality,HangoverFood',
      strYoutube: 'https://www.youtube.com/watch?v=UVAMAoA2_WU',
      strIngredient1: 'Vegetable Oil',
      strIngredient2: 'Beef Gravy',
      strIngredient3: 'Potatoes',
      strIngredient4: 'Cheese Curds',
      strIngredient5: '',
      strIngredient6: '',
      strIngredient7: '',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: 'Dash',
      strMeasure2: '1 Can',
      strMeasure3: '5 thin cut',
      strMeasure4: '2 cups',
      strMeasure5: '',
      strMeasure6: '',
      strMeasure7: '',
      strMeasure8: '',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'http://www.food.com/recipe/real-canadian-poutine-113388',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null
    },
  ]
}

export const mockMealsThree = {
  meals: [
    {
      idMeal: '52917',
      strMeal: 'White chocolate creme brulee',
      strDrinkAlternate: null,
      strCategory: 'Dessert',
      strArea: 'French',
      strInstructions: 'Heat the cream, chocolate and vanilla pod in a pan until the chocolate has melted. Take off the heat and allow to infuse for 10 mins, scraping the pod seeds into the cream. If using the vanilla extract, add straight away. Heat oven to 160C/fan 140C/gas 3.\r\n' +
        'Beat yolks and sugar until pale. stir in the chocolate cream. Strain into a jug and pour into ramekins. Place in a deep roasting tray and pour boiling water halfway up the sides. Bake for 15-20 mins until just set with a wobbly centre. Chill in the fridge for at least 4 hrs.\r\n' +
        'To serve, sprinkle some sugar on top of the brûlées and caramelise with a blowtorch or briefly under a hot grill. Leave caramel to harden, then serve.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uryqru1511798039.jpg',
      strTags: 'Desert,DinnerParty,Pudding',
      strYoutube: 'https://www.youtube.com/watch?v=LmJ0lsPLHDc',
      strIngredient1: 'Double Cream',
      strIngredient2: 'White Chocolate Chips',
      strIngredient3: 'Vanilla',
      strIngredient4: 'Egg Yolks',
      strIngredient5: 'Caster Sugar',
      strIngredient6: 'Caster Sugar',
      strIngredient7: '',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '568ml',
      strMeasure2: '100g ',
      strMeasure3: 'Pod of',
      strMeasure4: '6',
      strMeasure5: '2 tbs',
      strMeasure6: 'Top',
      strMeasure7: '',
      strMeasure8: '',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://www.bbcgoodfood.com/recipes/2540/white-chocolate-crme-brle',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null
    },
    {
      idMeal: '52948',
      strMeal: 'Wontons',
      strDrinkAlternate: null,
      strCategory: 'Pork',
      strArea: 'Chinese',
      strInstructions: 'Combine pork, garlic, ginger, soy sauce, sesame oil, and vegetables in a bowl.\r\n' +
        'Separate wonton skins.\r\n' +
        'Place a heaping teaspoon of filling in the center of the wonton.\r\n' +
        'Brush water on 2 borders of the skin, covering 1/4 inch from the edge.\r\n' +
        'Fold skin over to form a triangle, sealing edges.\r\n' +
        'Pinch the two long outside points together.\r\n' +
        'Heat oil to 450 degrees and fry 4 to 5 at a time until golden.\r\n' +
        'Drain and serve with sauce.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1525876468.jpg',
      strTags: 'MainMeal',
      strYoutube: 'https://www.youtube.com/watch?v=9h9No18ZyCI',
      strIngredient1: 'Pork',
      strIngredient2: 'Garlic Clove',
      strIngredient3: 'Ginger',
      strIngredient4: 'Soy Sauce',
      strIngredient5: 'Sesame Seed Oil',
      strIngredient6: 'Carrots',
      strIngredient7: 'Celery',
      strIngredient8: 'Spring Onions',
      strIngredient9: 'Wonton Skin',
      strIngredient10: 'Oil',
      strIngredient11: 'Water',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1lb',
      strMeasure2: '3 chopped',
      strMeasure3: '1 tsp ',
      strMeasure4: '1 tbs',
      strMeasure5: '1 tsp ',
      strMeasure6: '3 finely chopped',
      strMeasure7: '3 finely chopped',
      strMeasure8: '6 chopped',
      strMeasure9: '1 Packet',
      strMeasure10: 'Fry',
      strMeasure11: 'Bottle',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'http://www.geniuskitchen.com/recipe/chinese-wontons-20235',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null
    },
    {
      idMeal: '53062',
      strMeal: 'Walnut Roll Gužvara',
      strDrinkAlternate: null,
      strCategory: 'Dessert',
      strArea: 'Croatian',
      strInstructions: 'Mix all the ingredients for the dough together and knead well. Cover the dough and put to rise until doubled in size which should take about 2 hours. Knock back the dough and knead lightly.\r\n' +
        '\r\n' +
        'Divide the dough into two equal pieces; roll each piece into an oblong about 12 inches by 8 inches. Mix the filling ingredients together and divide between the dough, spreading over each piece. Roll up the oblongs as tightly as possible to give two 12 inch sausages. Place these side by side, touching each other, on a greased baking sheet. Cover and leave to rise for about 40 minutes. Heat oven to 200ºC (425ºF). Bake for 30-35 minutes until well risen and golden brown. Bread should sound hollow when the base is tapped.\r\n' +
        '\r\n' +
        'Remove from oven and brush the hot bread top with milk. Sift with a generous covering of icing sugar.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/u9l7k81628771647.jpg',
      strTags: 'Nutty',
      strYoutube: 'https://www.youtube.com/watch?v=Q_akngSJVrQ',
      strIngredient1: 'Flour',
      strIngredient2: 'Caster Sugar',
      strIngredient3: 'Yeast',
      strIngredient4: 'Salt',
      strIngredient5: 'Milk',
      strIngredient6: 'Eggs',
      strIngredient7: 'Butter',
      strIngredient8: 'Walnuts',
      strIngredient9: 'Butter',
      strIngredient10: 'Brown Sugar',
      strIngredient11: 'Cinnamon',
      strIngredient12: 'Milk',
      strIngredient13: 'Icing Sugar',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '450g',
      strMeasure2: '55g',
      strMeasure3: '2 parts ',
      strMeasure4: '1/2 tsp',
      strMeasure5: '6 oz ',
      strMeasure6: '2 Beaten ',
      strMeasure7: '30g',
      strMeasure8: '140g',
      strMeasure9: '85g',
      strMeasure10: '85g',
      strMeasure11: '1 tsp ',
      strMeasure12: 'To Glaze',
      strMeasure13: 'To Glaze',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://www.visit-croatia.co.uk/croatian-cuisine/croatian-recipes/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null
    }
  ]
}
