export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN2 = 'USER_LOGIN';

export const MEALS = 'MEALS';
export const COCKTAILS = 'COCKTAILS';

export const MEALS_CATEGORIES = 'MEALS_CATEGORIES';
export const COCKTAILS_CATEGORIES = 'COCKTAILS_CATEGORIES';

export const FILTERED_DRINKS = 'FILTERED_DRINKS';
export const FILTERED_FOODS = 'FILTERED_FOODS';

export const BUTTON_TOGGLE = 'BUTTON_TOGGLE';
